	private Integer roomType;//
	private Integer roomNo;//
    private Integer occupancy;//
	private String bedType;//
	private String availability;//
	private Integer price;
	private String amenities;//
	private Integer roomSize;
	private String view;//
	private String description;//
	private Integer floor;